### PR TITLE
Initial sketch for config/routes.rb

### LINKED ISSUE #11: Agree on routes file

### PR DESCRIPTION
**Pull request by wlffann**
This is our initial plan for the routes that will be needed. Routes will determine file structre

Closes #11

### CODE REVIEW

**Comment by wlffann** [comment]
Output of `rake routes`:

routes

**Comment by CPowell23** [comment]
Can someone remind me again, why did we decide to put pins outside instead of nesting them inside of boards? I was thinking that pins were unique to boards. So if somebody decides to add a pin to their board, they would actually be creating a copy of that pin and adding it to their board (it would be a separate instance).

**Comment by akintner** [comment]
I think pins exist outside of boards and can just "float" around on their own, but also can be added to a board or unpinned from one.

**Comment by CPowell23** [comment]
If that is true, our database is not going to like that as is. Since we put the t.references :board on the pins migration, it has to have a board.

**Comment by akintner** [comment]
@wlffann and @lucyconklin Looks like there's no boards_like functionality. Not sure if I am recalling correctly, but I thought users could "like" a whole board, and that doesn't seem to be on there. But maybe if a user "likes" another user then they defacto have "liked" the boards? Not sure.

**Comment by lucyconklin** [comment]
@CPowell23 pins exist outside boards because pins can have many boards. They will each have their own route, that way we don't have copies of one pin, but just associations. That's how Pinterest does it, (ex: https://www.pinterest.com/pin/319192692326272872/ ).

@akintner re: board likes. Actually I think that will be handled in this path:

registered_users     POST    /:username/:name    registered_users/like#create

...we will need to pull out your username, the board's name and the board's owner's name from the params, and have some logic in the controller that sets the target type and id.

This would mean that only logged in users can like, but that makes sense to me.

**Comment by wlffann** [comment]
@CPowell23 @lucyconklin @akintner We had a lot of discussion about pins and whether the same Pin on two different boards would be two different rows in the table. I was my understanding that they would be two different Pins, and the relationship between Boards and Pins was has_many, belongs_to. 

That being said, the routes can stay as they are with `/pins/:id` being the Pin's show. If we have the Pin, we can still pull up `@pin.board` and `@pin.board.registered_user`

**Comment by lucyconklin** [comment]
@wlffann Ok, I think you are right.

Under this scenario, a user could have their own description on a pin, which is also the design we want.

I wonder how Pinterest does it? It seems silly to have that same image saved to a database 1000 times when it could be saved just once with it's link.

**Comment by akintner** [comment]
Whoop.

**Pull request merged**
